- name: Run long-running command asynchronously
  hosts: ceph_cluster
  gather_facts: yes
  vars:
    drv_ssn_stdout_lines:
      - "FW333120"
      - "FW333121"
      - "FW333122"
      - "FW333123"
      - "FW333124"
      - "FW333125"
      - "FW333126"
      - "FW333127"
      - "FW333128"
      - "FW333129"
      - "FW333130"
      - "FW333131"
    mytest: "hello,world,nihao,daye"
  tasks:
  - name: Add user_defined labels to hosts
    debug:
      msg: "ceph orch host label add {{ inventory_hostname }} {{ item }}"
    loop: "{{ hostvars[inventory_hostname].label | from_yaml }}"
    when: hostvars[inventory_hostname].label is defined
    delegate_to: "{{ groups['ceph_cluster'][0] }}"
